#!/bin/bash
# damato 2014


PROGNAME=${0##*/}
PROGVERSION=0.1
declare VOLUME=100  # volume of speech 0-100
declare LOOP=0      # number of times to repeat end message, 0=forever
declare ALARM="Time to go upstairs!" # alarm message
declare DEBUG=
declare LEFT # time until next warning

usage()
{
  cat << EO
minutes-left [-m] minutes [options]
EO

  cat <<EO | column -s\& -t

  -h, --help & show this output
  -m, --minutes & minutes to count down
  -v, --volume & audio volume (0-100)
  -r, --repeat & how many times to repeat final alarm (0=forever)
  -a, --alarm-message & text to be spoken at the end of the countdown
  -d, --debug & skip delays during countdown

EO
}

SHORTOPTS="hdm:v:r:a:"
LONGOPTS="help,minutes:,volume:,repeat:,alarm-message:,debug"

ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")

eval set -- "$ARGS"

while true; do
    case $1 in
        -h|--help)
            usage; exit 0;;
        -v|--volume)
            VOLUME=$2; shift;;
	-r|--repeat)
	    LOOP=$2; shift;;
	-a|--alarm-message)
	    ALARM="$2"; shift;;
	-d|--debug)
	    DEBUG="true";;
	-m|--minutes)
	    LEFT=$2; shift;;
        --)
            LEFT=$2; break;;
    esac
    shift
done

(( LEFT > 0 )) || { usage; exit 1; }

[ $DEBUG ] && cat <<EOF | column -s\& -t

VOLUME & $VOLUME
LOOP & $LOOP
ALARM & $ALARM
MINUTES & $LEFT
DEBUG & $DEBUG
EOF


#(( $1 )) || { echo "usage: minutes-left MINUTES [ VOLUME [ LOOP [ SKIP-SLEEP ]]]"; exit; }

set -e
declare MSG
declare SLEEP



function repeat () { 
  mplayer -volume $VOLUME -loop $1 \
    -quiet -nolirc -prefer-ipv4 \
    "http://translate.google.com/translate_tts?tl=en&q=${@:2}" \
    > /dev/null; # only show stderr from mplayer
}

function say () { repeat 1 "$*"; }


while (( LEFT > 0 )); do

  MSG="$LEFT minute"
  (( LEFT > 1 )) && MSG="${MSG}s"
  MSG="${MSG} left"
  echo $MSG
  say "$MSG" > /dev/null
  SLEEP=$(( $LEFT ))
  LEFT=$(( 2 * LEFT / 3))
  echo "Next warning at $LEFT minutes left"
  SLEEP=$(( SLEEP - LEFT ))
  echo "Sleeping for $SLEEP minutes"
  (( $DEBUG )) || sleep $(( SLEEP * 60 ))

done

while (( 1 )); do

  repeat $LOOP "$ALARM" > /dev/null

done 
