#!/bin/bash
TARGET="$1"
if [[ "$TARGET" =~ ^[0-9]+$ ]] ; then
  TARGET="10.18.3.$TARGET"
  echo $TARGET
fi 
H="$TARGET"
# geometry of current window
#CURRENT_G=$(A=$(mktemp); echo -ne "\033]0;$A\007"; sleep 0.1; xwininfo -name "$A"|awk '/Width:/{printf "%sx",$2}/Height:/{ printf "%s",$2}')

RDPUSER=""

xfreerdp -K --no-nla --ignore-certificate $2 $3 $4 $5 -g 1800x1000 $TARGET &
#C="rdesktop -K -g 1800x950 -u $U -p $P ${D:+-d $D} $H"
#echo $C
#nohup $C > "nohup-$H.out" &
#cat "nohup-$H.out"
#echo $?
