#!/bin/bash
A=$(mktemp)
echo -ne "\033]0;$A\007"
sleep 0.1
eval $( xwininfo -name "$A"|awk '/Width:/{printf "GEOM=%sx",$2}/Height:/{ print $2}/id:/{ print "XID=" $4 }')
xfreerdp -g $GEOM --no-nla --ignore-certificate $* &
echo $?
