#!/bin/bash
set	-x
yum	install	pcmanfm	rxvt-unicode	volumeicon	xfce4-volumed	stalonetray gmrun scrot geeqie

# cat	<<-	'EOF'	>>	~/.Xresources
# 	URxvt.colorIT:	#87af5f
# 	URxvt.colorBD:	#d7d7d7
# 	URxvt.colorUL:	#87afd7
# 	EOF
